---
title: "Day7"
output: html_document
date: "2023-09-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
par(mfrow = c(1,4))
hist(duration, breaks = 3, freq = FALSE, ylim = c(0,1), col = "pink")
hist(duration, breaks = 6, freq = FALSE, ylim = c(0,1), col = "pink")
hist(duration, breaks = 12, freq = FALSE, ylim = c(0,1), col = "pink")
hist(duration, breaks = 24, freq = FALSE, ylim = c(0,1), col = "pink")
```

```{r}
xi <- c(2.1, 2.2, 2.3, 2.4, 2.6, 2.7, 3.2, 3.3, 3.6, 3.7)
n <- length(xi)
h <- 0.3
x <- seq(from = min(xi)-1, to = max(xi) + 1, length.out = 800)
gauss <- function(x){1/sqrt(2*pi)*exp(-(x^2)/2)}
shapes <- sapply(xi, function(xi){1/(h*n)*gauss((x-xi)/h)})
par(mfrow = c(1,2))
plot(x, apply(shapes, 1, sum), type = "l", ylab = "", lwd = 3)
hist(xi, breaks = 10, freq = FALSE, xlim = c(1,4))
```

```{r}
par(mfrow = c(1,2))
hist(xi, breaks = 10, freq = FALSE, xlim = c(1,4))
plot(density(xi, kernel = "gaussian"), xlim = c(1,4))
```
```{r}
par(mfrow = c(1,2))
with(data = geyser, hist(waiting, freq = FALSE, col = "grey95"))
with(data = geyser, lines(density(waiting), col = "red", lwd = 2))
with(data = geyser, plot(density(waiting), col = "red", lwd = 2, main = "Density of waiting"))
```

